### PR TITLE
Added automatic versioning via setuptools_scm

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by TomCrypto** [comment]
Thanks, that seems pretty useful for easily tracking versions. It's cool that it automatically picks up on tags, means I can easily create a tag before uploading to pypi and otherwise just use development versions when prototyping!

**Comment by prologic** [comment]
Yeap that's the idea; means you don't have to manually manage this i n a file; it's done for you! Just tag the repo!

**Comment by TomCrypto** [comment]
I noticed that the `version` argument to the ArgumentParser does not seem to work in Python 3.4, I changed it slightly to use an argument with action "version" which does the same thing but portably:

```
parser.add_argument('-v', '--version', action='version', version=version)
```

**Comment by prologic** [comment]
:+1: I di dnot know this about the Python 3 version of `argparse` :)

**Pull request merged**
